{{- if .Values.prometheusScraping.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "aws-service-quotas-exporter.fullname" . }}
  labels:
  {{- include "aws-service-quotas-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "aws-service-quotas-exporter.fullname" . }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - targetPort: {{ .Values.containers.ports.containerPort }}
    path: {{ .Values.prometheusScraping.path }}
    interval: {{ .Values.prometheusScraping.interval | quote }}
{{- end }}