name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for semvar
        uses: actions/setup-node@v2.1.4
      - uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - uses: actions/setup-go@v2
      - name: Run semantic-release
        run: npx -p @semantic-release/changelog -p semantic-release@17.3.0 -p @semantic-release/git semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get tag
        id: gettag
        uses: "WyriHaximus/github-action-get-previous-tag@1.0.0"
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          load: true
          context: .
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.gettag.outputs.tag }}
      - name: Scan Image
        continue-on-error: true
        uses: azure/container-scan@v0.1
        with:
          image-name: ghcr.io/${{ github.repository }}:${{ steps.gettag.outputs.tag }}
          severity-threshold: MEDIUM